---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# gp-001-ycclt-911calls

<!-- badges: start -->
An MIT license was used for this app. This requires preservation of copyright and license notice. Copyright holder name is under Tyler Halliwell.
<!-- badges: end -->

The goal of gp-001-ycclt-911calls is to analyze 911 call data sourced by the 5 boroughs of NYC. This app will allow you to visualize and interpret data and possibly make policy decisions.

How do I use it?

R and preferably RStudio is needed to run the app. 

How do I get it?

Contacting one of the authors is the best way to receive permission to run the app. The files are stored on a shared GitHub account, so the authors can grant you access to pull the files to use the app.

Authors:
 - Yuka Chen - yc8322a@student.american.edu
 
 - Chaytanya Kumar - ck2340a@student.american.edu
 
 - Tyler Halliwell - th3013a@students.american.edu
 
 - Concillia Mpofu - cm0789a@students.american.edu
 
 - Liberty Mudzingwa - lm7832a@students.american.edu
 
 

