

```{r}
library(tidycensus)
library(tidyverse)
library(keyring)
```


```{r}
#key_set("CENSUS_API_KEY_SECURE")
```

```{r}
#key_get("CENSUS_API_KEY_SECURE")
```

# NYC Survay data

```{r}
# Searching for the income Variable

#acs52020 <- load_variables(2020, "acs5", cache = TRUE)
```

```{r}
# US- 5-year Survey data
# Median Income in NYC counties
# Estimate!!Median income in the past 12 months --!!Total living in area 1 year ago:
USMedianInc <- get_acs(geography = "county",
                   state = "NY", 
                   variables = "B07411_001",
                   year = 2020,
                   key = key_get("CENSUS_API_KEY_SECURE"))
```


```{r}
USMedianInc %>%
  filter(NAME %in% c("Bronx County, New York",
                     "Kings County, New York",
                     "New York County, New York",
                     "Queens County, New York",
                     "Richmond County, New York"))-> NYCincome
NYCincome %>%
  mutate(NAME = gsub(" County, New York", "", NAME))->NYCincome

NYCincome%>%
  select(NAME,estimate,moe) ->
  NYCincome
```


```{r}
NYCincome %>%
  mutate(NAME = gsub(" County, New York", "", NAME)) %>%
  ggplot(aes(x = estimate, y = reorder(NAME, estimate))) +
  geom_point(color = "red", size = 3) +
  labs(title = "Median income by county in New York",
       subtitle = "2020 American Community Survey",
       y = "County/Borough",
       x = "Median Income")
```






# NYC Population data
```{r}
# 2020 NYC Census data
# Pop2020a <- load_variables(2020, "pl", cache = TRUE)
```

```{r}
USpop <- get_decennial(geography = "county",
                   variables = "P1_001N",
                   year = 2020,
                   key = key_get("CENSUS_API_KEY_SECURE"))
```


```{r}
USpop %>%
  filter(NAME %in% c("Bronx County, New York",
                     "Kings County, New York",
                     "New York County, New York",
                     "Queens County, New York",
                     "Richmond County, New York"))-> NYCpop
NYCpop %>%
  mutate(NAME = gsub(" County, New York", "", NAME))->NYCpop

NYCpop%>%
  select(NAME,value)->
  NYCpop
```



```{r}
NYCpop %>%
  mutate(NAME = gsub(" County, New York", "", NAME)) %>%
  ggplot(aes(x = value, y = reorder(NAME, value))) +
  geom_point(color = "red", size = 3) +
  labs(title = "Population by county in New York",
       subtitle = "2020 American Community Survey",
       y = "County/Borough",
       x = "Population")
```





```{r}
df_merge<- merge(NYCincome,NYCpop, by = "NAME")

df_merge %>%
  select(County=NAME, population= value, medianIncome = estimate, Income_moe = moe)-> NYCpop_income_data
#NYCpop_income_data$County <- as.factor(NYCpop_income_data$County)

NYCpop_income_data%>%
  mutate(County = fct_recode(as.factor(NYCpop_income_data$County),
                             BRONX    = "Bronx",
                             BROOKLYN = "Kings",
                             MANHATTAN = "New York",
                             QUEENS = "Queens",
                             'STATEN ISLAND'= "Richmond")
         ) -> NYCpop_income_data
```


```{r}
str(NYCpop_income_data)
```


```{r}
saveRDS(NYCpop_income_data, file = "Censusdata.RDS") 
```














