---
title: "Progress Report - gp-001-YCCLT-911 Calls"
author: "Tyler Halliwell, Yuka Chen, Chaytanya Kumar, Concillia Mpofu, and Liberty Mudzingwa"
date: "`r Sys.Date()`"
output: html_document
  
---
### <span style="color: blue;">Report.1. Admin:</span>



#### -  App Title: `NYC 911 Calls Summary`


#### -  Names and course of the group members:

 - Tyler Halliwell - DATA 613-001
 - Yuka Chen - DATA 613-001
 - Chaytanya Kumar - DATA 613-001
 - Concillia Mpofu - DATA 613-001
 - Liberty Mudzingwa - DATA 613-001
     
     
     
### <span style="color: blue;">Report.2. Topic and Data:</span>

#### -  Updates on the description of the problem to be analyzed in the Shiny App: 
 
The app is to discover most reported crime by NYC residents and the most frequent reported periods. As well as to see correlation between reported crime with median income.

#### -  Updates on proposed data sources and status of data collection, cleaning, and tidying:
 - primary data is pulled by API from NYC Open Data "https://data.cityofnewyork.us/Public-Safety/NYPD-Calls-for-Service-Year-to-Date-/n2zq-pubd".
    - we used `slice_sample()` from `{dplyr}` and took 200k random sample saved as csv file under data folder.
    - It generally takes 30~50 minutes to load whole 6M+ data on R (rmd in data-raw)
    - We tried to load the random data directly to our mega data but there are no solution
       - Link: "https://stackoverflow.com/questions/71820322/pull-random-sample-from-api-in-r"
 - secondary data is from package `{tidycensus}`.
    - we are able to call out the NYC median income by county. still figuring out the codes for the `get_acs()` for more information.

#### - Updates on the literature review:

 https://rviews.rstudio.com/2019/10/09/building-interactive-world-maps-in-shiny/
This article goes into great detail on how to build an interactive map. This is a good guide for us to use - we obviously cannot and will not use everything in this, but it is a good starting point.

https://www.pubadvocate.nyc.gov/reports/improving-new-york-citys-responses-to-individuals-in-mental-health-crisis/
This paper reviews 179,569 emergency calls relating to mental health in NYC in 2018. The paper reviews how calls are managed and how the city allocates support. They give their opinion on NYC's approach to mental health support during a crisis. They also give their recommendations on how to fix the city's issues.
 
### <span style="color: blue;">Report.3. Final Use Case:</span>

#### - Actor Description: 

 - Primary App Actor: Government Official for Urban Development.
 - Secondary App Actor: NYC Construction Company and Realtors 
 - Tertiary App Actor: NYC Residences
 
#### - Questions of Interest: 

Does median income for each borough influence the reported crime rate?
 
#### - Choice of approach to data: 

Selecting different variables for data summarization and interactive map.
 


### <span style="color: blue;">Report.4. App Design:</span> 

#### - General Layout with specific Tabs and Panes within Tabs:

Draft layout is at the shiny folder.

### <span style="color: blue;">Report.6. Ethical Review:</span> 

#### - Update of ethics review:

This shiny app's primary data source is collected by Intergraph Computer Aided Dispatch System (ICAD), a sysyem from NYC Police Department which recorded the call takers and dispatchers use to communicate with callers and the NYPD. Each record represents an entry into the system. The data includes entries generated by members of the public as well as self-initiated entries by NYPD Members of Service. It is possible that the records were not accurate or actually happened since the public also have the access to generate the record entries.  
 
Data from NYC OpenData is grouped into five NYC Boroughs that are of different economic classes(by GDP and income levels), different racial demographics and gender ratios. The analysis from our app gives summarized statistics of the daily rate and severity of criminal offences in different boroughs and may lead to economic, racial and gender segregation hence our app should be reserved for a few individuals who will make ethical use of the app, i.e for the allocation/assigning of appropriate security forces to areas of demand during certain times to minimize crime rate.
 
Data from NYC OpenData “does not warranty the completeness, accuracy, content, or fitness for any particular purpose”. We as the app developers, and NYC, are not liable for any deficiencies in the completeness, accuracy, content, or fitness for any particular purpose or use of the public data set. Since our app uses data from “NYC OpenData”, we need to pass this message onto the users.


 
### <span style="color: blue;">Report.7.Demonstration Outline and Responsibilities:</span> 

#### - Outline, Who and Time Allocation:
   - Data Cleaning and Tidying: Yuka and Liberty.
     - an hour ~ 2 hours per day
   - Shiny Layout: Connie and Chaytanya - The draft layout is found in the Shiny App folder. 
   - Data and App description, Lit Review: Tyler.
   
   
   
### <span style="color: blue;">Report.8. Collaboration:</span>  

#### - Status of collaboration and any issues
  - We have constant communication through WhatsApp.
  - We have regular weekly Zoom meeting during the weekend.
 
 
 
### <span style="color: blue;">Report.9. Schedule and Risk Mitigation:</span>  

#### - Identify any major risks to completion and proposed mitigation measures
  - The biggest risk right now is how to load whole data for our shiny app when we complete with sample data. 
  - Sample data might not contain all the information we originally wanted.
  - All members have high work load during final, it is challenging to do all the work simultaneously. 
 
#### - Updated Dates for Major Phases and Milestones:
 
   - Data cleaning and exploration: 4/15
   - Data manipulation and shiny structure: 4/19
   - Rough draft of app and Vignette: 4/25
   - Rehearsals on 4/31 and 5/1
   - Push to GitHub on 5/1
 


 
 
