---
title: "Vignette - gp-001-YCCLT-911 Calls"
author: "Tyler Halliwell, Yuka Chen, Chaytanya Kumar, Concillia Mpofu, and Liberty Mudzingwa"
date: "`r Sys.Date()`"
output: html_document
  
---
### <span style="color: blue;"> NYC 911 Calls Summary</span>


     
     
### <span style="color: blue;">Topic and Data:</span>

The point of this app is to analyze 911 calls in New York City. When a NYC resident dials 911, they are connected with a city operator and all data from that call goes into a system called ICAD. ICAD is used by the New York Police Department to obtain information about the reason for the call.

With this app, we would like to study the reported crimes or incidents called in by NYC residents. Important subsets of this data include Borough or time.


#### -  Updates on proposed data sources and status of data collection, cleaning, and tidying:
 - primary data is pulled by API from NYC Open Data "https://data.cityofnewyork.us/Public-Safety/NYPD-Calls-for-Service-Year-to-Date-/n2zq-pubd".
    - we used `slice_sample()` from `{dplyr}` and took 200k random sample saved as csv file under data folder.
    - It generally takes 30~50 minutes to load whole 6M+ data on R (rmd in data-raw)
    - We tried to load the random data directly to our mega data but there are no solution
       - Link: "https://stackoverflow.com/questions/71820322/pull-random-sample-from-api-in-r"
 - secondary data is from package `{tidycensus}`.
    - we are able to call out the NYC median income by county. still figuring out the codes for the `get_acs()` for more information.

### <span style="color: blue;">Literature:</span>

 https://rviews.rstudio.com/2019/10/09/building-interactive-world-maps-in-shiny/
This article goes into great detail on how to build an interactive map. This is a good guide for us to use - we obviously cannot and will not use everything in this, but it is a good starting point.

https://ibo.nyc.ny.us/cgi-park2/2019/05/theres-a-call-reporting-a-crime-in-progress-how-long-does-it-take-for-the-police-to-send-a-car-in-your-precinct/
This study measures the dispatch time between 911 operator and responding officers by precinct. This study uses 2018 data and reports by each of the 77 precincts in the city.

https://pubmed.ncbi.nlm.nih.gov/26075668/
This report was used as a benchmark for our Chi Squared test

https://www.pubadvocate.nyc.gov/reports/improving-new-york-citys-responses-to-individuals-in-mental-health-crisis/
This paper reviews 179,569 emergency calls relating to mental health in NYC in 2018. The paper reviews how calls are managed and how the city allocates support. They give their opinion on NYC's approach to mental health support during a crisis. They also give their recommendations on how to fix the city's issues.
 
### <span style="color: blue;">Data Description:</span>

#### - Data Description

 - boro_nm: Name of the Borough
 - progress:
 - Tertiary App Actor: NYC Residences
 
### <span style="color: blue;"> App Design:</span> 
 
#### - Tab Description

 - Variable Summary: User can see descriptive statistics on call volume by chosen variable
 
 - Time Series: This tab has 3 sub-tabs, but all three sub-tabs give the user an understanding of call volume and reports over time. 
 -- Months
 -- Hours
 -- Gap Time Summary: This tab shows the time it took officers to arrive to the reported scene. The time to report was created by subtracting the arrive time from the call time. There were a few instances where the reported arrival time was before the call time, but these were removed.
 
 -
 
 - Map: The map tab shows a map of the greater NYC area. There are bubbles over each of the NYC boroughs. The diameter of the circle represents the size/amount of the chosen variable.
 
### <span style="color: blue;">Coding and Libraries:</span>

 - shiny: The layout of the app relies heavily on shiny functions
 - tidyverse: many of the cleaning and plotting functions that were used in the app comes from the tidyverse
 - maps:
 - leaflet:
 - ggthemes:
 - maps:

### <span style="color: blue;">Packages Used:</span>
 
#### - Packages

 - boro_nm: Name of the Borough
 - progress:
 - Tertiary App Actor: NYC Residences



#### - General Layout with specific Tabs and Panes within Tabs:

Draft layout is at the shiny folder.

### <span style="color: blue;">Report.6. Ethical Review:</span> 

#### - Update of ethics review:

This shiny app's primary data source is collected by Intergraph Computer Aided Dispatch System (ICAD), a sysyem from NYC Police Department which recorded the call takers and dispatchers use to communicate with callers and the NYPD. Each record represents an entry into the system. The data includes entries generated by members of the public as well as self-initiated entries by NYPD Members of Service. It is possible that the records were not accurate or actually happened since the public also have the access to generate the record entries.  
 
Data from NYC OpenData is grouped into five NYC Boroughs that are of different economic classes(by GDP and income levels), different racial demographics and gender ratios. The analysis from our app gives summarized statistics of the daily rate and severity of criminal offences in different boroughs and may lead to economic, racial and gender segregation hence our app should be reserved for a few individuals who will make ethical use of the app, i.e for the allocation/assigning of appropriate security forces to areas of demand during certain times to minimize crime rate.
 
Data from NYC OpenData “does not warranty the completeness, accuracy, content, or fitness for any particular purpose”. We as the app developers, and NYC, are not liable for any deficiencies in the completeness, accuracy, content, or fitness for any particular purpose or use of the public data set. Since our app uses data from “NYC OpenData”, we need to pass this message onto the users.


 
### <span style="color: blue;">Report.7.Demonstration Outline and Responsibilities:</span> 

#### - Outline, Who and Time Allocation:
   - Data Cleaning and Tidying: Yuka and Liberty.
     - an hour ~ 2 hours per day
   - Shiny Layout: Connie and Chaytanya - The draft layout is found in the Shiny App folder. 
   - Data and App description, Lit Review: Tyler.
   
   
   
### <span style="color: blue;">Report.8. Collaboration:</span>  

#### - Status of collaboration and any issues
  - We have constant communication through WhatsApp.
  - We have regular weekly Zoom meeting during the weekend.
 
 
 
### <span style="color: blue;">Report.9. Schedule and Risk Mitigation:</span>  

#### - Identify any major risks to completion and proposed mitigation measures
  - The biggest risk right now is how to load whole data for our shiny app when we complete with sample data. 
  - Sample data might not contain all the information we originally wanted.
  - All members have high work load during final, it is challenging to do all the work simultaneously. 
 

 


 
 
